### ISSUE TITLE
Statusübersicht Abstand Indikatoren

### ISSUE THREAD

**Issue by Linder-S** [DnsUpgradeEnvironment/dns-indicators#22]
Ich fände es besser, wenn ein bisschen mehr Abstand zwischen den einzelnen Indikatoren wäre. Dann wären es einfacher erkennbar wann ein neuer Indikator anfängt.

**Comment by MoBosse** [comment]
@Linder-S Guter Punkt. Sollte hiermit erledigt sein. Falls nicht ok, bitte Issue erneut öffnen.
