### ISSUE TITLE
Suchfunktion Ergebnisse

### ISSUE THREAD

**Issue by Linder-S** [DnsUpgradeEnvironment/dns-indicators#26]
Nach der Suche steht zwischen dem Suchfeld und der Ergebniss-Liste z.B. 2: (die 2 ist die Anzahl der Ergebnisse).
Kann man hier einen Text wie zum Beispiel "Anzahl der gefundenen Ergebnisse: 2" einfügen?

**Comment by MoBosse** [comment]
@Linder-S Erledigt
