### ISSUE TITLE
Über uns - DNS-Online-Plattform

### ISSUE THREAD

**Issue by Linder-S** [DnsUpgradeEnvironment/dns-indicators#27]
Unter dem Punkt Über Uns - DNS Online-Plattform steht ein falscher Text. Hier werden nur SDGs beschrieben.

**Comment by MoBosse** [comment]
@Linder-S Ich glaube jetzt stimmt es, oder?

**Comment by Linder-S** [comment]
Ja, jetzt stimmt es.
