### ISSUE TITLE
Menü Wissenswertes - Veröffentlichungen

### ISSUE THREAD

**Issue by Linder-S** [DnsUpgradeEnvironment/dns-indicators#30]
Im Menü steht hier Veröffentlichungen, die Überschrift der Seite ist Publikationen.
Ich finde es besser, wenn hier einheitlich der gleiche Begriff verwendt wird. Vorschlag: Veröffentlichungen in Publikationen ändern.

**Comment by MoBosse** [comment]
@Linder-S Erledigt
