### ISSUE TITLE
Englische Seite Publications

### ISSUE THREAD

**Issue by Linder-S** [DnsUpgradeEnvironment/dns-indicators#31]
Hier steht der deutsche Text

**Comment by MoBosse** [comment]
@Linder-S Hier weiß ich leider nicht was du meinst.
Hier ist doch alles Englisch: https://dnsupgradeenvironment.github.io/dns-indicators/en/facts_publications/ 
Oder übersehe ich was?

**Comment by Linder-S** [comment]
Komisch. Bei mir war es vorgestern auch auf der englischen Seite auf deutsch. Jetzt ist es richtig.
Hat sich damit erledigt.
